-- 인덱스 삭제 
DROP INDEX IDX_EMP_SAL;

-- 테이블 뷰
-- 뷰란? 가상 테이블로 부르는 뷰는 하나 이상의 테이블을 조회하는 SELECT문을 저장한 개객체를 읨한다.
-- SELECT * FROM VW_EMP20;

SELECT *
	FROM(
		SELECT EMPNO, ENAME, JOB, DEPTNO 
		FROM EMP 
		WHERE DEPTNO = 20 
);

CREATE VIEW VW_EMP20 
AS (SELECT EMPNO, ENAME, JOB, DEPTNO 
	FROM EMP 
	WHERE DEPTNO = 20
);
	
-- 규칙에 따라 순번을 생성하는 시퀀스 
-- 시퀀스 : 오라클 데이터베이스에서 특정 규칙에 맞는 연속 숫자를 생성하는 객체 

CREATE TABLE DEPT_SEQUENCE 
AS SELECT * 
	FROM DEPT 
	WHERE 1<>1;
	
-- 시퀀스 생성하기 
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 10 
START WITH 10 
MAXVALUE 90 
MINVALUE 10
NOCYCLE
CACHE 2;

SELECT *FROM USER_SEQUENCES;

INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
	VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL,'DATABASE','SEOUL');
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
	VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL,'JAVA','SEOUL');
SELECT *FROM DEPT_SEQUENCE
ORDER BY DEPTNO;